apiVersion: v1
kind: Service
metadata:
  name: express-app
  namespace: default
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 10
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: express-app
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: express-app
spec:
  selector:
    matchLabels:
      app: express-app
  replicas: 1
  template:
    metadata:
      labels:
        app: express-app
        version: v1
    spec:
      containers:
        - name: express-app
          image: kix.ocir.io/axnnurxkc2v6/express-app:${BUILDRUN_HASH}
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 8080
